name: Java Backend CI/CD

# Automatically triggered on push or pull request events
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Job to set up Java and compile using Maven
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # Cache Maven dependencies for faster builds
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    # Compile using Maven
    - name: Compile with Maven
      run: mvn clean compile
    
    # Run tests
    - name: Run tests
      run: mvn test
    
    # Package the application
    - name: Package with Maven
      run: mvn package -DskipTests